---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: gcr.io/google-samples/node-hello:1.0
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /hello
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
